import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

import type { Family } from "./manifest.ts";
import { dirName } from "./util.ts";

/** Leading `/* ... *\/` banner cn-font-split writes at the top of each result.css. */
const HEADER_COMMENT = /^\s*\/\*[\s\S]*?\*\/\s*/;

/**
 * Build `fonts/<slug>/index.css`: every instance's `@font-face` rules inlined into one file, with
 * each relative chunk URL rewritten to point into its per-style sub-directory. Consumers can load
 * the whole family (all weights/styles, still lazy via `unicode-range`) from this single URL.
 */
export async function writeFamilyIndex(opts: {
  family: Family;
  familyDir: string;
  generator: string;
}): Promise<void> {
  const { family, familyDir, generator } = opts;

  const blocks: string[] = [];
  for (const instance of family.instances) {
    const dir = dirName(instance);
    const css = await readFile(join(familyDir, dir, "result.css"), "utf8");
    const body = css.replace(HEADER_COMMENT, "").trim();
    const rewritten = body
      .replaceAll('url("./', `url("./${dir}/`)
      .replaceAll("url('./", `url('./${dir}/`)
      .replaceAll("url(./", `url(./${dir}/`);
    blocks.push(
      `/* ${family.cssFamily} · ${String(instance.weight)} ${instance.style} */\n${rewritten}`,
    );
  }

  const banner =
    `/*! ${family.displayName} — all weights & styles.\n` +
    ` * font-family: "${family.cssFamily}"\n` +
    ` * Generated by ${generator}. Do not edit by hand.\n` +
    ` * Need just one weight? Use ./<weight>-<style>/result.css instead.\n` +
    ` */\n`;

  await writeFile(join(familyDir, "index.css"), `${banner}${blocks.join("\n\n")}\n`, "utf8");
}
