import { readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";

import type { Family, Instance } from "./manifest.ts";
import { dirName, stylesOf, weightsOf } from "./util.ts";

/** Leading `/* ... *\/` banner cn-font-split writes at the top of each result.css. */
const HEADER_COMMENT = /^\s*\/\*[\s\S]*?\*\/\s*/;

interface Block {
  instance: Instance;
  /** Per-cut sub-dir holding this instance's woff2 chunks, e.g. `400-normal`. */
  dir: string;
  /** The instance's @font-face rules: header stripped, url()s pointed into `./<dir>/`. */
  css: string;
}

/**
 * Read every instance's `<dir>/result.css` and rewrite its relative chunk URLs to point into the
 * per-cut sub-dir, so the same rules can be inlined into any entry-point file at the package root.
 */
async function readBlocks(family: Family, familyDir: string): Promise<Block[]> {
  const blocks: Block[] = [];
  for (const instance of family.instances) {
    const dir = dirName(instance);
    const raw = await readFile(join(familyDir, dir, "result.css"), "utf8");
    const body = raw.replace(HEADER_COMMENT, "").trim();
    const css = body
      .replaceAll('url("./', `url("./${dir}/`)
      .replaceAll("url('./", `url('./${dir}/`)
      .replaceAll("url(./", `url(./${dir}/`);
    blocks.push({ instance, dir, css });
  }
  return blocks;
}

/** Concatenate blocks, each tagged with a `family · weight style` comment. */
function joinBlocks(family: Family, blocks: Block[]): string {
  return blocks
    .map(
      (b) =>
        `/* ${family.cssFamily} · ${String(b.instance.weight)} ${b.instance.style} */\n${b.css}`,
    )
    .join("\n\n");
}

function banner(family: Family, generator: string, scope: string, hint: string): string {
  return (
    `/*! ${family.displayName} — ${scope}.\n` +
    ` * font-family: "${family.cssFamily}"\n` +
    ` * Generated by ${generator}. Do not edit by hand.\n` +
    ` * ${hint}\n` +
    ` */\n`
  );
}

/**
 * Emit the full grid of CSS entry points at the package root, all referencing the same shared woff2
 * chunks (no byte duplication — only the tiny @font-face text repeats):
 *
 *   index.css              all weights × all styles   (full bundle)
 *   weight-<weight>.css    one weight, all styles     (per-weight bundle)
 *   style-<style>.css      one style, all weights     (per-style bundle)
 *   <weight>-<style>.css   exactly one cut            (atomic)
 *
 * Consumers pick the narrowest file that covers what they use; every cut stays lazy via
 * `unicode-range`.
 */
export async function writeFamilyStyles(opts: {
  family: Family;
  familyDir: string;
  generator: string;
}): Promise<void> {
  const { family, familyDir, generator } = opts;
  const blocks = await readBlocks(family, familyDir);

  const write = async (
    name: string,
    scope: string,
    hint: string,
    picked: Block[],
  ): Promise<void> => {
    const css = `${banner(family, generator, scope, hint)}${joinBlocks(family, picked)}\n`;
    await writeFile(join(familyDir, name), css, "utf8");
  };

  // Atomic — one weight × one style.
  for (const b of blocks) {
    const { weight, style } = b.instance;
    await write(
      `${b.dir}.css`,
      `weight ${String(weight)}, ${style}`,
      `Whole family: ./index.css · this weight: ./weight-${String(weight)}.css · this style: ./style-${style}.css`,
      [b],
    );
  }

  // Per-weight bundle — one weight × all styles.
  for (const weight of weightsOf(family)) {
    await write(
      `weight-${String(weight)}.css`,
      `weight ${String(weight)}, all styles`,
      `Whole family: ./index.css · just one cut: ./${String(weight)}-<style>.css`,
      blocks.filter((b) => b.instance.weight === weight),
    );
  }

  // Per-style bundle — one style × all weights.
  for (const style of stylesOf(family)) {
    await write(
      `style-${style}.css`,
      `all weights, ${style}`,
      `Whole family: ./index.css · just one cut: ./<weight>-${style}.css`,
      blocks.filter((b) => b.instance.style === style),
    );
  }

  // Full bundle — all weights × all styles.
  await write(
    "index.css",
    "all weights & styles",
    "Need just one weight or style? Use ./weight-<weight>.css, ./style-<style>.css, or ./<weight>-<style>.css.",
    blocks,
  );

  // The per-cut `result.css` is now superseded by the root-level `./<weight>-<style>.css`; drop it so
  // we don't ship a second copy of every cut (the npm `files` allowlist globs `**/*.css`).
  for (const b of blocks) {
    await rm(join(familyDir, b.dir, "result.css"), { force: true });
  }
}
